{
 "title": "Envoy 全局大盘",
 "description": "Envoy全局大盘",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "应用",
    "query": "label_values(envoy_server_live, app)"
   },
   {
    "name": "ip",
    "label": "主机",
    "query": "label_values(envoy_server_live{app=\"$app\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "在线个数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_server_live{app=\"$app\",instance=~\"$ip\"})",
     "legendFormat": "Envoy"
    }
   ]
  },
  {
   "title": "平均运行时间",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(envoy_server_uptime{app=\"$app\",instance=~\"$ip\"})"
    }
   ]
  },
  {
   "title": "申请内存",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_server_memory_heap_size{app=\"$app\",instance=~\"$ip\"})"
    }
   ]
  },
  {
   "title": "线程个数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(envoy_server_concurrency{app=\"$app\",instance=~\"$ip\"})"
    }
   ]
  },
  {
   "title": "使用内存",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_server_memory_heap_size{app=\"$app\",instance=~\"$ip\"})",
     "legendFormat": "平均内存"
    }
   ]
  },
  {
   "title": "使用内存排行榜",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (app, group, instance) (envoy_server_memory_heap_size{app=\"$app\",instance=~\"$ip\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 }, "options": { "content": "<center><h2>流量</h2></center>" }, "content": "<center><h2>流量</h2></center>" },
  {
   "title": "Dubbo QPS (单位:次/秒)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m]))",
     "legendFormat": "Dubbo outbound QPS"
    }
   ]
  },
  {
   "title": "Dubbo 成功率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_response_success{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo outbound 成功率"
    }
   ]
  },
  {
   "title": "Dubbo 平均 RT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request_time_ms_sum{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request_time_ms_count{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo outbound 平均RT"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 7, "y": 17 },
   "options": {
    "content": "<center><h2>Outbound 流量</h2></center>"
   },
   "content": "<center><h2>Outbound 流量</h2></center>"
  },
  {
   "title": "Dubbo Outbound QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m]))",
     "legendFormat": "Dubbo outbound QPS (单位:次/秒)"
    }
   ]
  },
  {
   "title": "Dubbo Outbound 成功率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_response_success{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo outbound 成功率"
    }
   ]
  },
  {
   "title": "Dubbo Outbound 失败率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request_decoding_error{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 请求解码失败"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_response_error{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 响应错误"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_response_decoding_error{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 响应解码失败"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_response_business_exception{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 响应异常"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_response_error_caused_connection_close{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 连接关闭"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_local_response_error{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 本端响应错误"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_local_response_business_exception{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 本端响应异常"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_response_timeout{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 响应超时"
    }
   ]
  },
  {
   "title": "Dubbo Outbound RT 分布",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request_time_ms_bucket{app=\"$app\",instance=~\"$ip\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request_time_ms_bucket{app=\"$app\",instance=~\"$ip\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request_time_ms_bucket{app=\"$app\",instance=~\"$ip\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Dubbo Outbound 最低成功率",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bottomk(5, sum by(app, group, instance) ((rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_response_success{app=\"$app\",instance=~\"$ip\"}[1m])) / (rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m]))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dubbo Outbound 平均 RT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request_time_ms_sum{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_outbound_20880_request_time_ms_count{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "平均RT"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 10, "x": 7, "y": 32 },
   "options": {
    "content": "<center><h2>Inbound 流量</h2></center>"
   },
   "content": "<center><h2>Inbound 流量</h2></center>"
  },
  {
   "title": "Dubbo Inbound QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m]))",
     "legendFormat": "Dubbo inbound QPS (单位:次/秒)"
    }
   ]
  },
  {
   "title": "Dubbo  Inbound 成功率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_response_success{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo inbound 成功率"
    }
   ]
  },
  {
   "title": "Dubbo Inbound 失败率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request_decoding_error{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 请求解码失败"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_response_error{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 响应错误"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_response_decoding_error{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 响应解码失败"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_response_business_exception{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 响应异常"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_response_error_caused_connection_close{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 连接关闭"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_local_response_error{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 本端响应错误"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_local_response_business_exception{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 本端响应异常"
    },
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_response_timeout{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "Dubbo 响应超时"
    }
   ]
  },
  {
   "title": "Dubbo  Inbound RT 分布",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(irate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request_time_ms_bucket{app=\"$app\",instance=~\"$ip\"}[1m])) by (le))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request_time_ms_bucket{app=\"$app\",instance=~\"$ip\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request_time_ms_bucket{app=\"$app\",instance=~\"$ip\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Dubbo Inbound 最低成功率",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "bottomk(5, sum by(app, group, instance) ((rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_response_success{app=\"$app\",instance=~\"$ip\"}[1m])) / (rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request{app=\"$app\",instance=~\"$ip\"}[1m]))))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dubbo Inbound 平均 RT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request_time_ms_sum{app=\"$app\",instance=~\"$ip\"}[1m])) / sum(rate(envoy_dubbo_dubbo_incomming_stats_inbound_20880_request_time_ms_count{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "平均RT"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 10, "x": 7, "y": 47 }, "options": { "content": "<center><h2>xDS</h2></center>" }, "content": "<center><h2>xDS</h2></center>" },
  {
   "title": "xDS 更新成功",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_manager_cds_update_success{app=\"$app\",instance=~\"$ip\"}[1m]))",
     "legendFormat": "cds  (单位:次/S)"
    },
    {
     "expr": "sum(rate(envoy_listener_manager_lds_update_success{app=\"$app\",instance=~\"$ip\"}[1m]))",
     "legendFormat": "lds  (单位:次/S)"
    }
   ]
  },
  {
   "title": "xDS 更新失败",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(envoy_cluster_manager_cds_update_attempt{app=\"$app\",instance=~\"$ip\"}[1m])) - sum(irate(envoy_cluster_manager_cds_update_success{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "cds (单位:次/S)"
    },
    {
     "expr": "round(sum(irate(envoy_listener_manager_lds_update_attempt{app=\"$app\",instance=~\"$ip\"}[1m])) - sum(irate(envoy_listener_manager_lds_update_success{app=\"$app\",instance=~\"$ip\"}[1m])))",
     "legendFormat": "lds  (单位:次/S)"
    }
   ]
  },
  {
   "title": "xDS 连接数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{app=\"$app\",instance=~\"$ip\",cluster_name=\"xds-grpc\"})",
     "legendFormat": "xds-grpc (单位:个)"
    }
   ]
  }
 ]
}