apiVersion: v1
kind: Secret
metadata:
  name: service-registry-config
  namespace: istio-system
type: Opaque
data:
  config.json: >-
    =====
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: asm-se-syncer
    asm-system: "true"
    provider: asm
  name: asm-se-syncer
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asm-se-syncer
      asm-system: "true"
      provider: asm
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
        sidecar.istio.io/inject: "false"
      labels:
        app: asm-se-syncer
        asm-system: "true"
        provider: asm
    spec:
      automountServiceAccountToken: false
      containers:
        - args:
            - serve
            - --meshId=cf9e58cf8743748b3bd13867d6d87e30b
            - --regionId=cn-beijing
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: IS_SAME_VPC
              value: "false"
          image: registry.cn-hangzhou.aliyuncs.com/acs/asm-se-syncer:v0.1.dev
          imagePullPolicy: Always
          name: asm-se-syncer
          resources:
            limits:
              cpu: "2"
              memory: 2G
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /etc/istio/serviceregistry
              name: service-registry-config
              readOnly: true
      restartPolicy: Always
      volumes:
      - name: service-registry-config
        secret:
          defaultMode: 420
          optional: false
          secretName: service-registry-config