apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: httpbin
  namespace: {{ .Values.namespace }}
spec:
  host: httpbin
  subsets:
  {{- $indices := untilStep 1 (int (add .Values.deployReplicas 1)) 1 }}
  {{- range $indices }}
  - name: v{{ . }}
    labels:
      version: v{{ . }}
  {{- end }}