# Default values for alibaba-cloud-asm-se-syncer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# ASMID indicates the ASM instance ID (ref: https://servicemesh.console.aliyun.com/#/instances)
ASMID: ""
# RegionId indicates the region in which you Kubernetes cluster resides. For example, if the cluster resides in Hangzhou, the value of this parameter cn-hangzhou.
RegionId: ""
AccessKeyId: ""
AccessKeySecret: ""
SeSyncerImage:
  Repository: "registry.cn-hangzhou.aliyuncs.com/acs/asm-se-syncer"
  Tag: "v1.0.0.32-gabc59eb-aliyun"
Resources:
  # default limit for ASM-SE-Syncer
  Limits:
    Cpu: 2
    Memory: 2G
  # request for ASM-SE-Syncer
  Requests:
    Cpu: 200m
    Memory: 256Mi
Consul: |-
  [
    {
      "name": "consul-test",
      "prefix": "consul-",
      "type": "consul",
      "endpoint": "http://consul-server.consul:8500",
      "toNamespace": "default"
    }
  ]
